### PR TITLE
Add custom styles as an option

### PR DESCRIPTION
**Pull request by stefnnn**
Hi Fabian,

Glad I found NativeTachyons, I really like the concept and was working on a similar idea and then stumbled on your project. I do see the beauty in the simplicity of tachyons, but I do feel slightly constrained by at times. That's why I built an option to pass custom styles in NativeTachyons.build(). 

Does that somehow fit into your vision?

### CODE REVIEW

**Comment by fab1an** [comment]
Why don't you just use string-templates:

```jsx
/* possibly in external file */
const custom = "bg-green"

<View cls={`flx-i ml5 $custom`} />

```

**Comment by stefnnn** [comment]
Sounds like an alternative indeed. I do like the fact, that you can combine tachyon snippets instead of falling back to css and having to do the REM scaling manually. 

I don't particularly like the syntax though with the backticks, curlies & $.

What about passing in options.shortcuts, a     of strings, which are then expanded?

**Comment by fab1an** [comment]
Not sure. In doubt, I'd rather not add features, because I don't want it to be so powerful that I can write styles that I don't comprehend with a single glance a year later.

I will think about it. Please do comment if you have further ideas.

**Comment by fab1an** [comment]
I've decided to not include this.

What you are proposing is basically adding classes which combine multiple style-directives. 
A core principle of tachyons however is to have single purpose-classes only. A nice write-up about this can be found here: http://mrmrs.io/writing/2016/03/24/scalable-css/

One could argue that the custom classes are optional, however I don't want to encourage people to use them.

Perhaps you should check out https://github.com/vitalets/react-native-extended-stylesheet for more flexible styling.

**Comment by stefnnn** [comment]
I can follow your thinking. Thanks for taking the time to reason about it :thumbsup:

React-native-extended-stylesheet is a bit beyond my taste in terms of complexity. I'll continue the quest for a well balanced approach - which of course is also highly subjective.

**Comment by fab1an** [comment]
Alright, keep me posted!

**Pull request closed without merging**
